version: '3.8'

services:
  metrics_exporter:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: metrics_exporter
    ports:
      - "8000:8000"
    volumes:
      - ../logs:/app/logs  # Map local logs directory to container
    command: uvicorn src.app.metrics_exporter:app --reload --host 0.0.0.0 --port 8000
    networks:
      - monitoring
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set default admin password
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:

volumes:
  grafana_data:  # Named volume for Grafana data persistence