version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ENV=production
    volumes:
      - ../src/app:/app
      - ../logs:/logs
    networks:
      - infrauditai-network

networks:
  infrauditai-network:
    driver: bridge