apiVersion: apps/v1
kind: Deployment
metadata:
  name: infraauditai-deployment
  labels:
    app: infraauditai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infraauditai
  template:
    metadata:
      labels:
        app: infraauditai
    spec:
      containers:
      - name: infraauditai
        image: infraauditai:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "250m"
